# -*- coding: utf-8 -*-
"""parent-child-retreiver-drill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9CHp1HTA71VEuwqv-Fkp-CA3J82HDa0
"""

!pip install faiss-cpu sentence-transformers

'''
Pseudocode

C: input: documents, output: string (parent and child)printed
O:

* prepare 2-3 policy style document and store in the folder
* split the documents in 1500 to 2000 chars chunks
* generate parent id for each chunk
* store parent chunks in a plain dict of docstore {id: chunk}
* process each chunk again and split into 300-400chars chunk
* set metadata per each child chunk with parent id
* keep a separate python list child_index → parent_id (this seems to teach me more instead of a readymade wrapper to do the mapping for me)
* store the child as embedding into the vector db
* send query and embed it
* check the embedded one against the children and find the top child
* lookup the parent id and pull the chunk
* print the child and its parent

D:

* parents -> Dict(id: text)[docstore]
* children -> list of child texts (to be embedded)
* child_metadata -> parallel list of parent's dict per child chunk
* embeddings -> FAISS index(children vectors)
* Query -> single string converted to an embedding vector
'''

#Split policies into parent chunks

file_path = "/content/sample_data/cash_flow_policy.txt"
with open(file_path, "r") as f:
  text_content = f.read()

print(f"Successfully read the document {file_path}")

parent_chunks = {}
counter = 0
for i in range(0, len(text_content), 2000):
  start = i
  end = i + 2000
  parent_id = f"cash_flow_parent_{counter}"
  parent_text = text_content[start:end]
  parent_chunks[parent_id] = parent_text
  counter += 1

print(parent_chunks)

child_metadata = []
child_chunks = []
#child_counter = 0

for id, chunk in parent_chunks.items():
  for i in range(0, len(chunk), 350):
    start = i
    end = i + 350
    child_metadata.append(id) # Fix: use append instead of direct assignment
    child_text = chunk[start:end]
    child_chunks.append(child_text) # Fix: use append instead of direct assignment
    #child_counter += 1

print(len(child_chunks), child_chunks[0], child_metadata[0])

!pip install faiss-cpu sentence-transformers

from sentence_transformers import SentenceTransformer
import faiss


# Load the 'all-MiniLM-L6-v2' model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model 'all-MiniLM-L6-v2' loaded successfully.")

dim = embedding_model.get_embedding_dimension()

child_chunk_embeddings = embedding_model.encode(child_chunks).astype('float32')
print("Child chunk embeddings generated successfully.")

print(dim)
index = faiss.IndexFlatL2(dim)
print("FAISS index created successfully.")

index.add(child_chunk_embeddings)
print(index.ntotal)

query = "What is the early payment discount?"
embedded_query = embedding_model.encode([query]).astype("float32")

result_distance, result_position = index.search(embedded_query, k=1)
print(result_distance, result_position)

child_position = result_position[0][0]
print(child_position)

matched_child = child_chunks[child_position]
matched_parent = child_metadata[child_position]

parent_chunk = parent_chunks[matched_parent]

print(f"child text: \n {matched_child}\n")
print(f"parent text: \n {parent_chunk}")